---
title: "Adverse Events"
resource_files:
- .httr-oauth .Renviron
- .httr-oauth
- .Renviron
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    css: styles.css
    orientation: columns
    theme: readable
    vertical_layout: fill
---



```{r setup, include=FALSE}
library(flexdashboard)
library(stringr)
library(bigrquery)
library(openfda)
library(dplyr)
library(dbplyr)
library(DBI)
library(ggplot2)
library(ggthemes)

con <- dbConnect(
  bigrquery::bigquery(),
  project = 'bigquery-public-data',
  dataset = 'nlm_rxnorm',
  billing = bq_test_project()
)
pathways <- tbl(con, 'rxn_all_pathways_01_18')

# Get all brand name drugs from BigQuery
all_names <- pathways %>% 
  filter(TARGET_TTY == 'BN') %>% 
  select(TARGET_NAME) %>% 
  group_by(TARGET_NAME) %>% 
  summarise() %>% 
  collect()

get_adverse <- function(gender, brand_name, age) {
  fda_query("/drug/event.json") %>%
    fda_filter("patient.drug.openfda.brand_name", brand_name) %>% 
    fda_filter("patient.patientsex", gender) %>% 
    fda_filter("patient.patientonsetage", age) %>% 
    fda_count("patient.reaction.reactionmeddrapt.exact") %>% 
    fda_limit(10) %>% 
    fda_exec()
}


create_age <- function(min, max){#
  sprintf('[%d+TO+%d]', min, max)
}
```

Column {.sidebar}
------------

```{r inputs}


selectizeInput('sel_name', 'Brand Name Drug', all_names)

sliderInput('ages', 'Age Range', min = 10, max = 80, value = c(20,60))


ingredients <- reactive({ pathways %>%
  filter(TARGET_NAME == input$sel_name, TARGET_TTY == 'BN', SOURCE_TTY %in% c('IN', 'SY')) %>% 
  select(SOURCE_NAME, SOURCE_TTY) %>% 
  collect()
})

age <- reactive({create_age(input$ages[1],input$ages[2])})

male <- reactive({
  ad <- get_adverse("1", input$sel_name, age())
  if (!is.null(ad)) {
    ad$gender = 'male'
  }
  ad
})

female <- reactive({
  ad <- get_adverse("2", input$sel_name, age())
  if (!is.null(ad)) {
    ad$gender = 'female'
  }
  ad
})

adverse <- reactive({
  req(male(), female())
  rbind(male(), female())
})

```

Column {data-width=650}
-----------------------------------------------------------------------

### All Events

```{r}
renderPlot({
  req(adverse())
  adverse() %>% 
  group_by(term) %>% 
  summarise(count = sum(count)) %>% 
  ggplot() +
    geom_bar(aes(reorder(term,count), count), stat = 'identity') +
    coord_flip() +
    labs(
      title = input$sel_name,
      x = NULL,
      y = NULL
    ) +
    theme_minimal()
})

```


### Events by Gender

```{r}
renderPlot({
  req(adverse())
  ggplot(adverse()) +
    geom_bar(aes(reorder(term,count), count, fill = gender), stat = 'identity') +
    facet_wrap(~gender)+
    coord_flip() +
    labs(
      title = input$sel_name,
      x = NULL,
      y = NULL
    ) +
    theme_minimal() + 
    guides(fill = FALSE) + 
    scale_fill_manual(values = c("#d54a30","#4c83b6"))
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Age Range

```{r}
age_label <- reactive({
  str_replace_all(age(), fixed("+"), " ") %>% 
    str_replace(fixed("["), "") %>% 
    str_replace(fixed("]"), "") %>% 
    str_replace(fixed("TO"), "-")     
})
renderValueBox({valueBox(age_label(), icon = 'fa-flask', color = "#4c83b6")})
```

### {.no-title}

```{r}
DT::renderDataTable({
  DT::datatable(ingredients() %>% select(`Active Ingredients` = SOURCE_NAME),   
                options = list(dom = "t"))
})
```

